### ISSUE TITLE
Link events to their canonical url

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/the-trans-dimension#381]
## User story

As someone who wants to go to an event on The Trans Dimension, I want a link directly from the event to the source URL e.g. ticketing link or webpage if it exists, in order that I don't have to faff around with going on their website and finding it twice

## Acceptance criteria

- [ ] [Events](https://transdimension.uk/events/329484/) link to [original pages](https://dalstonsuperstore.com/event/haute-mess-5/)

## Implementation plan

**Comment by katjam** [comment]
This related conversation on an earlier attempt to build this might be helpful. https://github.com/GenderedIntelligence/the-trans-dimension/issues/223

**Comment by kimadactyl** [comment]
nice. this was my first actual user story as someone actually using the app to find an event to go to 🥲

**Comment by katjam** [comment]
This is a `good first issue` if the data is reliable and there from PlaceCal.

**Comment by james-collapse** [comment]
@katjam Just to make sure I've understood - PlaceCal already includes a button that links to the event website on the event page, but there isn't a similar button on the Trans Dimension site. So is the job to add a similar button to the Trans Dimension site?

![Screenshot 2024-09-07 at 11 27 41](https://github.com/user-attachments/assets/34facd04-4811-4408-832b-6afdf464d1f4)
![Screenshot 2024-09-07 at 11 27 25](https://github.com/user-attachments/assets/2123cda5-0c76-49b0-aae2-2635820c85ab)

**Comment by katjam** [comment]
Yes. That's right. When we built The Trans Dimension, we could not reliably get that info from the data but we now think we can.

> @katjam Just to make sure I've understood - PlaceCal already includes a button that links to the event website on the event page, but there isn't a similar button on the Trans Dimension site. So is the job to add a similar button to the Trans Dimension site?
> 
> ![Screenshot 2024-09-07 at 11 27 41](https://private-user-images.githubusercontent.com/117429670/365360875-34facd04-4811-4408-832b-6afdf464d1f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4Nzg3MTEsIm5iZiI6MTcyNTg3ODQxMSwicGF0aCI6Ii8xMTc0Mjk2NzAvMzY1MzYwODc1LTM0ZmFjZDA0LTQ4MTEtNDQwOC04MzJiLTZhZmRmNDY0ZDFmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxMDQwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmU1NjY3NzY1ZTJhMDYyYjNkODY4ZTg2YjYzOThhZjVhOWRjMWEzODc4N2JjOGIyOGNmZTUwMGUyNjIwYmI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MPWqpTg935GS7wqE1zpn_2KSYXlZSfYppxlJZ5XCym8) ![Screenshot 2024-09-07 at 11 27 25](https://private-user-images.githubusercontent.com/117429670/365360879-2123cda5-0c76-49b0-aae2-2635820c85ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4Nzg3MTEsIm5iZiI6MTcyNTg3ODQxMSwicGF0aCI6Ii8xMTc0Mjk2NzAvMzY1MzYwODc5LTIxMjNjZGE1LTBjNzYtNDliMC1hYWUyLTI2MzU4MjBjODVhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxMDQwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTI5NzFiZTkwZTkzZjFkNmE1MDdmZmU4OGEyOGZlNWU3MDgyYWFiM2JiNGVkMTNmOTU0OTQ0MDIyYTE4YTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hdc4NKgM7z75LdVNhbNRszXXNV_conbo6W9SfHm7sh8)

**Comment by katjam** [comment]
Yes. That's right. When we built The Trans Dimension, we could not reliably get that info from the data but we now think we can.

> @katjam Just to make sure I've understood - PlaceCal already includes a button that links to the event website on the event page, but there isn't a similar button on the Trans Dimension site. So is the job to add a similar button to the Trans Dimension site?

**Comment by katjam** [comment]
You may need to wait untill I get Events rendering in the new build system but if you want to get going, you can branch off `main` and I we can port the change in once Events are in `staging`.

**Comment by james-collapse** [comment]
@katjam have you managed to get Events rendering in the new build system yet?

**Comment by katjam** [comment]
> @katjam have you managed to get Events rendering in the new build system yet?

Yes. I believe I have - but not tested it out much yet.

**Comment by katjam** [comment]
There is also this recently raised issue that could be worth considering in conjunction. It's one of some complication reasons we shelved this before. https://github.com/geeksforsocialchange/PlaceCal/issues/2614

Look into the use of the `Realm` type I think Jazz started putting this in place with the intention of Realm being virtual vs realword

**Comment by james-collapse** [comment]
@katjam Just sharing the fruits of my investigation so far:

1. The Event page already renders a link to the `publisherUrl` if one exists (see `publisherUrlSection` in `src/Theme/EventPage`), although it's not very prominent;
2. Some events have a link in the `publisherUrl`, but others have a link in the `onlineEventUrl` - for example:

```
{
  "id": "392420",
  "name": "Beginner Pasta Workshop",
  "onlineEventUrl": null,
  "onlineEventUrlType": null,
  "publisherUrl": "https://www.eventbrite.co.uk/e/beginner-pasta-workshop-tickets-1023677666457"
},
{
  "id": "392550",
  "name": "BodySwap",
  "onlineEventUrl": "https://dalstonsuperstore.com/event/bodyswap-47/",
  "onlineEventUrlType": "indirect",
  "publisherUrl": null
}
```

This seems weird to me - I wouldn't expect there to be two places where a link could potentially appear. Is there a good justification for this?

**Comment by kimadactyl** [comment]
@katjam - this one might be needed for release too, we have a lot of people using ticketing site pages and its weird if they cant easily get to the event page

**Comment by katjam** [comment]
Have we confirmed for sure that the data is usable for this. I know we've had a lot of conversations various places around it.

**Comment by kimadactyl** [comment]
> This seems weird to me - I wouldn't expect there to be two places where a link could potentially appear. Is there a good justification for this?

my memory of this is very foggy and i remember being very uncomfy with the OnlineEvent stuff being added, but i think this in theory is just because the event zoom or youtube link or whatever might be different to the ticket link

**Comment by katjam** [comment]
OK great. I'll close this then and we can verify that the publisherUrl is indeed being rendered.
