### ISSUE TITLE
Review of copy that indicates Trans Dimension is for London

### ISSUE THREAD

**Issue by studiosquid** [geeksforsocialchange/the-trans-dimension#409]
## Description

This was discussed between Katja and Mark — not sure who's action it is, but copy may need revision to reflect a change to a non solely London focus across the site.

## Acceptance Criteria

- [x] Descriptions on github reflect the addition of Manchester
- [x] The home and about pages in https://transdimension.uk are not London centric
- [ ] [TBC] Announce in GFSC studio website / socials that Trans Dim now includes Manchester
- [ ] Project info about Trans Dimension on GFSC website isn't London centric
- [ ] [TBC] Gendered Intelligence mention that Trans Dimension includes Manchester
- [ ] [TBC] Mailing list descriptions make clear that Trans Dimension is not only London

## Plan

- [ ] Review copy on homepage and about pages to adjust from London centric language.
- [ ] Amend AC as appropriate
- [ ] Make the code changes
- [ ] Make appropriate tasks for non-code changes

**Comment by kimadactyl** [comment]
oh - marking things as done in huly is marking them done in here. need to decide if this is desirable functionality or not and change our processes if so. tbh it makes sense to me that we mark issues when we have a PR open, there's no need for them to be so hard coupled with the merge and it makes it clearer which tickets are open.

**Comment by katjam** [comment]
I'm happy with what ever makes it easiest for you - as long as we have away of knowing which issues need verifying before a release to prod.

**Comment by kimadactyl** [comment]
slightly confusingly, huly milestones are mapped to github projects too - need to spent a bit of time looking at how they think you should be doing this lol. i am really liking it in general tho, everything is unifed into one stream of tasks to do, and it prompts you to actually schedule tasks in whcih i think is prob very healthy for my adhd lol. just yeah some interesting decisions there
