### ISSUE TITLE
Track transdimension.uk donations separately

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/the-trans-dimension#411]
Was acceptance for #272 that maybe got overlooked.

Also might be a good idea to link to the GI donations page rather than direct to Just giving at this point.

**Comment by katjam** [comment]
Question is how we do this? Does Plausible show outgoing links?

**Comment by kimadactyl** [comment]
> Question is how we do this? Does Plausible show outgoing links? Does Just Giving show source?

I think no and no - adding this to the current milestone at the bottom as if we do do a dec fundraiser this feels kinda important to have. I would imagine min implementation is some kind of Stripe thing.

**Comment by kimadactyl** [comment]
Oh yeah quinn reccomended this which should just be a copy/paste form and some account signup: https://donorbox.org/

**Comment by kimadactyl** [comment]
OK I've signed up for an account on [donorbox](https://donorbox.org) - login in bitwarden. Need to connect stripe but let's check its as easy to integrate as it looks first, theres a range of options. I think the popup sticky donation button looks the most promising / least faff to integrate for which the code is:

```html
<script type="text/javascript" defer="" src="https://donorbox.org/install-popup-button.js" id="donorbox-popup-button-installer" data-href="https://donorbox.org/the-trans-dimension?default_interval=o" data-style="background: rgb(4, 15, 57); color: rgb(255, 255, 255); text-decoration: none; font-family: Verdana, sans-serif; display: flex; font-size: 16px; padding: 8px 22px 8px 18px; border-radius: 0px 0px 5px 5px; gap: 8px; width: fit-content; line-height: 24px; position: fixed; top: 50%; transform-origin: center center 0px; z-index: 9999; overflow: hidden; left: 20px; transform: translate(-50%, -50%) rotate(-90deg);" data-img-src="https://donorbox.org/images/white_logo.svg"> </script>
```

if we just want a regular button this is the code given:

```html
<a class="dbox-donation-page-button" href="https://donorbox.org/the-trans-dimension?default_interval=o" style="background: rgb(4, 15, 57); color: rgb(255, 255, 255); text-decoration: none; font-family: Verdana, sans-serif; display: flex; font-size: 16px; padding: 8px 24px; border-radius: 5px; gap: 8px; width: fit-content; line-height: 24px;"><img src="https://donorbox.org/images/white_logo.svg" style="">Donate</a>
```

**Comment by kimadactyl** [comment]
Let's work under the assumption we are going to switch donations to us for this unless we hear otherwise before the end of month.
