### ISSUE TITLE
Consider moving Trans Dim into GFSC GitHub

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/the-trans-dimension#434]
## Use case

This started out as more GIs thing but if GFSC are going to be the maintainers and project leads on TransDim, I think it makes sense to have it hosted and run from the GFSC GitHub repo. This means that we will have proper control over permissions and github groups and generally give us more flexibility with getting volunteer support and the like, and also means we don't have to go hunting for it when we are trying to find the repo.

## Acceptance criteria

- [ ] Migrate repo to GFSC org
- [ ] Update CI builds
- [ ] Migrate permissions

**Comment by kimadactyl** [comment]
@katjam - can we do this when we go live? i think this is a must given we're moving more to volunteer labour. we can't be adding randoms to GI's github team!

**Comment by katjam** [comment]
It's pretty easy to move. Everything should come across when we transfer from one org to the other, but of course no change is without uncertainty.

Couple things to think about:
1- do we need the charity status for any github features we use
2- if outside folks want to contribute they should maybe be doing it through remote forks anyway

**Comment by kimadactyl** [comment]
GFSC has a charity acct too now :)

agree on the remote forks. main point is we should be controlling it with GFSC permissions not GI ones.

the only thing im worried about is cloudflare builds getting confused when we do it!

**Comment by katjam** [comment]
I'm pretty sure cloudflare will "just work".

Nice GFSC got classed as a charity, how'd you manage that?

**Comment by katjam** [comment]
Yep - go for it.

**Comment by kimadactyl** [comment]
OK done!
