### ISSUE TITLE
Once I've selected Manchester, it stays selected when I change the page

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/the-trans-dimension#470]
Continuation of: https://github.com/geeksforsocialchange/the-trans-dimension/issues/466

<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU1YTM4OTFlMDYzMmRkMDhlMjU3NzkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.mGKuAQmbCc87-is2kk7PvwhA_n2MznYz4YCLYRuKIA4">Huly&reg;: <b>TD-471</b></a></sub>

**Comment by kimadactyl** [comment]
Note that this should work on browser back button too (unsure where AC for this now live)
