### ISSUE TITLE
[Bug]: Partner event listings are showing inconsistent interface and date browsers

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/the-trans-dimension#473]
## Description

Looking at individual partners, the events browsers are in some cases showing a full day browser (whcih is way overkill) or in some cases indicating a day has been selected when it's not.

These should just list all future events instead. Assume this got a bit scrambled when the changeover happened.

<img width="1181" src="https://github.com/user-attachments/assets/960ade95-c14d-4f1c-8d14-cf53ddf6f4d0" alt="Screenshot 2024-12-08 at 14 14 23">
<img width="1189" src="https://github.com/user-attachments/assets/d37458f4-b611-4de0-b754-c395974b5a39" alt="Screenshot 2024-12-08 at 14 15 23">

## Steps to reproduce

1. Visit https://transdimension.uk/partners/303
2. Visit https://transdimension.uk/partners/150

<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU1YWI2NzFlMDYzMmRkMDhlMjU4ODMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.jvIWUaOyEoKeBiLSubruD6X9hLTcscd24_E4-uGDMyE">Huly&reg;: <b>TD-474</b></a></sub>

**Comment by katjam** [comment]
https://github.com/geeksforsocialchange/the-trans-dimension/issues/206 some of the view events logic was lost when adding the region filter

**Comment by kimadactyl** [comment]
yeah i think just showing future events is great for now, a past button would be a nice extra but for another day :)

**Comment by katjam** [comment]
Actually, looking at the code, it's just that the logic for checking event numbers is happening before the filter is applied. So the path of least change might be to make sure the events are filtered for future before the branching. Previously the list was filtered before being passed to the component.

**Comment by katjam** [comment]
> yeah i think just showing future events is great for now, a past button would be a nice extra but for another day :)

Cool - I'll see which fix is less changes. Now that I've seen what is happening.
